language: cpp
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - gfortran-5
      env:
        - CXX_COMPILER='g++-5'
        - C_COMPILER='gcc-5'
        - Fortran_COMPILER='gfortran-5'
        - BUILD_TYPE='Release'
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - gfortran-6
      env:
        - CXX_COMPILER='g++-6'
        - C_COMPILER='gcc-6'
        - Fortran_COMPILER='gfortran-6'
        - BUILD_TYPE='Release'
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
            - gfortran-7
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - Fortran_COMPILER='gfortran-7'
        - BUILD_TYPE='Release'
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
            - gfortran-7
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - Fortran_COMPILER='gfortran-7'
        - BUILD_TYPE='Coverage'
    - os: osx
      compiler: clang
      env: BUILD_TYPE=RelWithDebInfo

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - test -n $FC && unset FC
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes update; fi
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install gfortran; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc; fi

install:
  - mkdir cnstream-build && cd cnstream-build
  # Configure
  - >
     cmake $TRAVIS_BUILD_DIR
     -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
     -DCMAKE_C_COMPILER=${C_COMPILER}
     -DCMAKE_Fortran_COMPILER=${Fortran_COMPILER}
     -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
     -DCMAKE_INSTALL_PREFIX=~/cnstream
  # Build
  - make

script:
  # Test the program
  - make test
  # Create package
  - make package
  # Make sure we can install with no issues.
  - make install
  # Create coverage report
  - if [[ "$BUILD_TYPE" == "Coverage" ]];
    then
    echo "Coverage";
    find $TRAVIS_BUILD_DIR -type f -name "*.gcno";
    find $TRAVIS_BUILD_DIR -type f -name "*.gcna";
    make coverage;
    bash <(curl -s https://codecov.io/bash) -X gcov;
    fi